version: "2.2"

services:
  postgres:
    image: postgres:10.7-alpine
    restart: always
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: hh
      POSTGRES_DB: hh
      POSTGRES_USER: hh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hh"]
      interval: 10s
      timeout: 5s
      retries: 5

  hh-homework-backend:
    image: woodlu/backend
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    ports:
      - "8080:8080"
